#150398701 Setup unit testing for front end
andela/isildur-cfh pull request #3
Opened 2017-08-23 12:27 UTC by Kenec

#### Set up unit testing for front-end
#### To ensure the front end has all functionality work the way it was intended.
#### To test this run: karma start
#### Setup unit testing for the front end

2017-08-23 17:23 UTC, VanPaitin requested changes
Looks good. Resolve merge conflicts by rebasing and then I will approve. Also note that you will have to get the build to pass

2017-08-24 16:16 UTC, Kenec commented
Merge conflict have been resolved by rebasing

2017-08-24 16:33 UTC, Kenec commented
Hound CI bot issue resolved

2017-08-24 19:26 UTC, VanPaitin approved these changes

2017-08-24 19:26 UTC, merged